export const LAB_TESTS = [
  { id: "CBC", category: "Hematology", name: "Complete Blood Count" },
  { id: "B_GLUCOSE", category: "Clinical Chemistry", name: "Blood Glucose (Fasting/Random)" },
  { id: "HBA1C", category: "Clinical Chemistry", name: "Glycated Hemoglobin (HbA1c)" },
  { id: "LFT", category: "Clinical Chemistry", name: "Liver Function Tests (ALT, AST, ALP, Bilirubin)" },
  { id: "RFT", category: "Clinical Chemistry", name: "Serum Creatinine & Blood Urea (RFT)" },
  { id: "LIPID", category: "Clinical Chemistry", name: "Lipid Profile" },
  { id: "URINALYSIS", category: "Clinical Chemistry", name: "Urinalysis" },
  { id: "XRAY", category: "Imaging / Radiology", name: "X-ray (Radiography)" },
  { id: "USG", category: "Imaging / Radiology", name: "Ultrasound Scan (Ultrasonography)" },
  { id: "CT_SCAN", category: "Imaging / Radiology", name: "Computed Tomography Scan (CT)" },
  { id: "MRI", category: "Imaging / Radiology", name: "Magnetic Resonance Imaging (MRI)" },
  { id: "ECG", category: "Cardiac / Cardiovascular", name: "Electrocardiogram (ECG)" },
  { id: "ECHO", category: "Cardiac / Cardiovascular", name: "Echocardiography" },
  { id: "B_CULTURE", category: "Microbiology", name: "Blood Culture" },
  { id: "U_CULTURE", category: "Microbiology", name: "Urine Culture" },
  { id: "MALARIA", category: "Microbiology", name: "Malaria Blood Smear" },
  { id: "TB_AFB", category: "Microbiology", name: "Tuberculosis GeneXpert / AFB Smear" },
  { id: "HIV", category: "Immunology / Serology", name: "HIV Test" },
  { id: "HEPATITIS", category: "Immunology / Serology", name: "Hepatitis Serology" },
  { id: "CRP", category: "Immunology / Serology", name: "C-Reactive Protein (CRP)" },
  { id: "TFT", category: "Endocrinology", name: "Thyroid Function Tests (TSH, T3, T4)" },
  { id: "PREGNANCY", category: "Gynecology & Maternity", name: "Pregnancy Test (Serum/Urine)" },
  { id: "BIOPSY", category: "Pathology", name: "Tissue Biopsy" }
];
