export type Language = 'EN' | 'AM';

export const TRANSLATIONS = {
  EN: {
    nav: {
      citizenRegistration: "Citizen Registration",
      citizenSignIn: "Sign-In / Portal",
      healthcareProfessionalPortal: "Healthcare Professional Portal",
      loggedInAs: "Logged in as",
      myHealthHistory: "My Health History",
      accessLogs: "Access Logs",
      privacySettings: "Privacy Settings",
      patientSearch: "Patient Search",
      clinicalRecords: "Clinical Records",
      emergencyTriage: "Emergency Triage",
    },
    landing: {
      title: "Universal Healthcare Access",
      subtitle: "Secure clinical network for all citizens.",
      registerCitizen: "Register Citizen",
      healthcareLogin: "Healthcare Professional Login",
      heroTitle: "One Patient. One Health Identity. Connected Care.",
      heroSubtitle: "MyHealthID connects patient identity, clinical workflows, and authorized care across healthcare facilities in Ethiopia.",
      faydaReady: "Fayda-Ready",
      identityIntegration: "identity integration",
      multiFacilityArch: "Multi-facility architecture",
      whatToDo: "What would you like to do?",
      selectPortal: "Select your portal to continue",
      startPatientIntake: "Start patient intake and identity verification",
      portalSignIn: "Portal Sign-In",
      accessWorkspace: "Access your clinical or facility workspace",
      onboardHospital: "Onboard Hospital",
      registerHospital: "Register your hospital or clinic",
      open: "Open \u2192",
      aboutInitiative: "About the Initiative",
      unifyingIdentity: "Unifying Identity and Health Delivery Across Ethiopia",
      persistentIdentity: "One persistent health identity",
      persistentIdentityDesc: "By bridging medical history directly with the National Fayda ID, the platform ensures seamless record portability across public and private hospitals.",
      captureVitals: "Capture vitals and prioritize",
      captureVitalsDesc: "Support clinical prioritization with intelligent triage workflows, maintaining the highest clinical integrity while citizen privacy remains strictly safeguarded.",
      coordinateWorkflows: "Coordinate clinical workflows",
      coordinateWorkflowsDesc: "Enable authorized practitioners to seamlessly manage reception, triage, doctor, laboratory, and pharmacy workflows dynamically.",
      supportContinuity: "Support authorized continuity",
      supportContinuityDesc: "Connect patients to authorized care across healthcare facilities with a multi-facility architecture designed for national scale.",
      fromFirstVisit: "From First Visit to Connected Care",
      howItWorks: "How MyHealthID Works",
      identify: "1. Identify",
      identifyDesc: "Create or verify the patient's MyHealthID",
      triage: "2. Triage",
      triageDesc: "Capture vitals and prioritize clinical attention",
      care: "3. Care",
      careDesc: "Connect reception, triage, doctor, lab and pharmacy",
      coordinate: "4. Coordinate",
      coordinateDesc: "Support authorized information sharing across facilities"
    },
    registration: {
      title: "Citizen Registration",
      subtitle: "Initialize a new secure citizen health record — Hybrid Identity Bridge",
      identityVerification: "Identity Verification",
      identitySelectionDesc: "How would you like to identify this citizen?",
      faydaIdTitle: "Fayda National ID",
      faydaIdDesc: "Citizen has a 12-digit Fayda ID",
      faydaPathTitle: "Fayda National ID Path",
      faydaPathDesc: "Enter and verify the citizen's 12-digit Fayda ID below",
      faydaVerificationRequired: "Fayda Verification Required",
      faydaUnlockText: "Please verify the Fayda National ID above to unlock the full registration form.",
      noIdTitle: "No National ID",
      noIdDesc: "Generate a unique MyHealthID — no citizen excluded",
      noIdPathTitle: "Auto-Generated MyHealthID Path",
      noIdPathDesc: "A unique internal UUID will be generated automatically",
      noIdBadgeText: "A unique MyHealthID will be auto-generated for this citizen upon registration. No ID required.",
      change: "Change",
      completeRegistration: "Complete Citizen Registration",
      registering: "Registering Citizen...",
      demographicsTitle: "1. Citizen Demographics",
      addressTitle: "2. Address & Contact Information",
      visitTitle: "3. Reason for Visit",
      duplicateWarning: "An official health profile is already linked to this information. Please navigate to the Sign-In / Portal panel to verify via SMS OTP securely.",
      goToSignIn: "Go to Sign-In",
      scheduleVisitTitle: "Schedule Clinical Visit",
      scheduleVisitDesc: "Book an outpatient appointment or queue check-in.",
      enterPortalTitle: "Enter Patient Portal",
      enterPortalDesc: "Access secure clinical records, test results, and medical logs."
    },
    login: {
      title: "Healthcare Professional Portal",
      subtitlePre: "Authenticate to access the MyHealth",
      subtitlePost: " secure clinical network.",
      emailLabel: "Professional Email / Username",
      passwordLabel: "Password",
      roleLabel: "Access Role",
      secureLogin: "Secure Login",
      selectCreds: "Select your credentials...",
      simNote: "Note: Simulation mode enabled. Any credentials accepted for demo."
    },
    signin: {
      title: "Citizen Sign-In Portal",
      subtitle: "Access your secure health dashboard using your MyHealthID or Fayda National ID.",
      idLabel: "Fayda ID or MyHealthID (MHI-)",
      idPlaceholder: "e.g. MHI-... or 12-digit Fayda ID",
      accessButton: "Access Health Dashboard",
      notFoundTitle: "Record Not Found",
      notFoundDesc: "No citizen found with this ID. Please check the ID or head over to the Citizen Registration page to create a new profile.",
      registerLink: "Go to Citizen Registration",
      otpTitle: "Enter Verification Code",
      otpSubtitle: "We sent a 6-digit verification code to your registered mobile number.",
      otpLabel: "6-Digit Code",
      otpPlaceholder: "e.g. 123456",
      verifyButton: "Verify & Enter Dashboard",
      verifying: "Verifying Code...",
      resendButton: "Resend Code",
      resendCountdown: "Resend Code ({seconds}s)",
      backButton: "Back to Login",
      otpSentTo: "Verification code sent to {phone}",
      invalidOtp: "The verification code is invalid or expired.",
      tooManyAttempts: "Too many failed attempts. Session blocked."
    },
    profile: {
      title: "Citizen Profile Self-Management",
      subtitle: "Update your contact and identification details securely.",
      editButton: "Edit Profile",
      saveButton: "Save Changes",
      cancelButton: "Cancel",
      fullNameLabel: "Full Name",
      phoneLabel: "Phone Number",
      dobLabel: "Date of Birth",
      successMessage: "Profile updated successfully!",
      errorMessage: "Failed to update profile. Please try again.",
      backToRecords: "Back to Clinical Records"
    },
    privacy: {
      title: "Privacy & Data Control",
      subtitle: "You own your health data. Control who sees it.",
      restrictToggle: "Restrict Access",
      restrictToggleAm: "መረጃን መገደብ",
      unrestrictToggle: "Allow Access",
      unrestrictToggleAm: "መዳረሻ ፍቀድ",
      restrictedBadge: "Restricted",
      openBadge: "Open",
      auditLogTitle: "Access Audit Log",
      auditLogSubtitle: "Every time a healthcare professional views your record, it is logged here.",
      colProfessional: "Professional",
      colFacility: "Facility",
      colRole: "Role",
      colAction: "Action",
      colTimestamp: "Timestamp",
      noLogs: "No access events recorded yet.",
      breakGlass: "Access Restricted by Patient",
      breakGlassDesc: "This patient has restricted access to their clinical records.",
      breakGlassBtn: "Request Emergency Override",
      breakGlassConfirm: "Emergency Override Activated — Access Granted & Logged",
    },
    registrationV2: {
      pageTitle: "Register Patient",
      pageSubtitle: "Create a new MyHealthID patient record.",
      // Mode Selector
      modeFayda: "Fayda ID",
      modeFaydaDesc: "Verify using Fayda national identification",
      modeNoId: "No National ID",
      modeNoIdDesc: "Auto-generate a secure MyHealthID",
      modeEmergency: "Emergency",
      modeEmergencyDesc: "Fast registration for urgent care",
      faydaUnavailable: "Fayda verification is not available in this environment.",
      faydaSandboxNote: "Sandbox mode — verification is not production government data.",
      // Fayda flow
      faydaStepBack: "Step 1: Scan QR code on the back of the Fayda card",
      faydaStepFront: "Step 2: Photograph the front of the card",
      faydaStepConfirm: "Step 3: Confirm identity",
      finLabel: "Fayda Identification Number (FIN)",
      finPlaceholder: "12-digit number on the back of the card",
      fcnLabel: "Fayda Card Number (FCN)",
      fcnPlaceholder: "16-digit number on the front barcode",
      verifyManual: "Verify",
      manualBypass: "Type FIN / FCN manually",
      scanBack: "Scan Back of Card",
      scanFront: "Photograph Front of Card",
      confirmIdentity: "Confirm Identity",
      verificationSuccess: "Identity verified",
      verifiedFrom: "Name, date of birth, and sex were confirmed from the Fayda registry.",
      // Basic info
      sectionBasicInfo: "Patient Information",
      fullNameLabel: "Full Name",
      fullNamePlaceholder: "Patient's full legal name",
      sexLabel: "Sex",
      sexMale: "Male",
      sexFemale: "Female",
      dobLabel: "Date of Birth",
      ageLabel: "Age",
      agePlaceholder: "Age in years",
      ageFromDob: "Age (calculated from date of birth)",
      phoneLabel: "Phone Number",
      phonePlaceholder: "09... (optional)",
      // Address
      sectionAddress: "Address",
      regionLabel: "Region",
      regionPlaceholder: "e.g. Addis Ababa, Amhara...",
      addressOptional: "Add more address details (optional)",
      zoneLabel: "Zone / Sub-city",
      woredaLabel: "Woreda",
      kebeleLabel: "Kebele",
      // Portal access
      portalAccessTitle: "Online Access (Optional)",
      portalAccessDesc: "Set a password so the patient can view their health records online. This can be done later.",
      passwordLabel: "Create Password",
      confirmPasswordLabel: "Confirm Password",
      passwordPlaceholder: "Min 6 characters",
      confirmPasswordPlaceholder: "Re-enter password",
      skipPortal: "Skip — Set Up Later",
      setPassword: "Set Password",
      showPassword: "Show",
      hidePassword: "Hide",
      // Emergency
      emergencyTitle: "Emergency Fast Registration",
      emergencyDesc: "Minimal information — patient enters emergency queue immediately.",
      emergencyNameLabel: "Patient Name",
      emergencyNamePlaceholder: "Full name (minimum 2 characters)",
      emergencyPhoneLabel: "Phone (Optional)",
      emergencyPhonePlaceholder: "09...",
      emergencySubmit: "Register Emergency Patient",
      emergencyRegistering: "Registering...",
      // Submit / Review
      completeRegistration: "Complete Registration",
      registering: "Registering...",
      // Duplicate warning
      duplicateWarning: "A patient record already exists with this information.",
      duplicateGoSignIn: "Sign In Instead →",
      // Success
      successTitle: "Patient Registered",
      mhidLabel: "MyHealthID",
      mhidExplainer: "This number identifies the patient across all MyHealthID services. Please make a note of it or scan the QR code.",
      copyId: "Copy",
      copied: "Copied!",
      queueLabel: "Queue",
      queuePosition: "Position",
      queueAdded: "Added to queue",
      priorityLabel: "Priority",
      priorityEmergency: "Emergency",
      priorityUrgent: "Urgent",
      priorityRoutine: "Routine",
      wardLabel: "Department",
      // Next actions
      actionTriage: "Continue to Triage",
      actionBookAppointment: "Book Appointment",
      actionOpenPortal: "Open Patient Portal",
      actionRegisterAnother: "Register Another Patient",
      actionSetupPortal: "Set Up Online Access",
    },
  },
  AM: {
    nav: {
      citizenRegistration: "የዜጎች ምዝገባ",
      citizenSignIn: "መግቢያ / ፖርታል",
      healthcareProfessionalPortal: "የጤና ባለሙያዎች ፖርታል",
      loggedInAs: "በዚህ ገብተዋል",
      myHealthHistory: "የጤና ታሪኬ",
      accessLogs: "የመዳረሻ መዝገቦች",
      privacySettings: "የግላዊነት ቅንብሮች",
      patientSearch: "የታካሚ ፍለጋ",
      clinicalRecords: "ክሊኒካዊ መዝገቦች",
      emergencyTriage: "አስቸኳይ ምርመራ",
    },
    landing: {
      title: "ሁለንተናዊ የጤና እንክብካቤ ተደራሽነት",
      subtitle: "ደህንነቱ የተጠበቀ የክሊኒክ ኔትወርክ ለሁሉም ዜጎች",
      registerCitizen: "የዜጎች ምዝገባ",
      healthcareLogin: "የጤና ባለሙያዎች መግቢያ",
      heroTitle: "አንድ ታካሚ። አንድ የጤና ማንነት። የተሳሰረ እንክብካቤ።",
      heroSubtitle: "MyHealthID በኢትዮጵያ ውስጥ ባሉ የጤና ተቋማት የታካሚ ማንነትን፣ ክሊኒካዊ የስራ ሂደቶችን እና የተፈቀደ እንክብካቤን ያገናኛል።",
      faydaReady: "ለፋይዳ ዝግጁ",
      identityIntegration: "የማንነት ውህደት",
      multiFacilityArch: "ባለ ብዙ-ተቋም አርክቴክቸር",
      whatToDo: "ምን ማድረግ ይፈልጋሉ?",
      selectPortal: "ለመቀጠል ፖርታልዎን ይምረጡ",
      startPatientIntake: "የታካሚ ምዝገባ እና የማንነት ማረጋገጫ ይጀምሩ",
      portalSignIn: "ፖርታል መግቢያ",
      accessWorkspace: "የክሊኒክ ወይም የተቋም የስራ ቦታዎን ይክፈቱ",
      onboardHospital: "ተቋም ይመዝገቡ",
      registerHospital: "ሆስፒታልዎን ወይም ክሊኒክዎን ይመዝገቡ",
      open: "ክፈት \u2192",
      aboutInitiative: "ስለ ፕሮግራሙ",
      unifyingIdentity: "በኢትዮጵያ ዙሪያ ማንነትን እና የጤና አሰጣጥን ማዋሃድ",
      persistentIdentity: "አንድ ቋሚ የጤና ማንነት",
      persistentIdentityDesc: "የህክምና ታሪክን ከፋይዳ ብሔራዊ መታወቂያ ጋር በማገናኘት፣ በመንግስት እና በግል ሆስፒታሎች መካከል தடைய የለሽ የመዝገብ ዝውውርን ያረጋግጣል።",
      captureVitals: "ምርመራ እና ቅድሚያ መስጠት",
      captureVitalsDesc: "የዜጎች ግላዊነት በጥብቅ እየተጠበቀ ከፍተኛ ክሊኒካዊ ትክክለኛነትን በመጠበቅ፣ በጥበብ የተሞላ የቅድሚያ አሰጣጥ (Triage) ስርዓትን ይደግፋል።",
      coordinateWorkflows: "ክሊኒካዊ የስራ ሂደቶችን ማቀናጀት",
      coordinateWorkflowsDesc: "የተፈቀደላቸው ባለሙያዎች የእንግዳ መቀበያ፣ ምርመራ፣ ሐኪም፣ ላቦራቶሪ እና ፋርማሲ ስራዎችን በተቀላጠፈ ሁኔታ እንዲያስተዳድሩ ያስችላቸዋል።",
      supportContinuity: "የተፈቀደ ቀጣይነትን መደገፍ",
      supportContinuityDesc: "ለሀገር አቀፍ ደረጃ ተብሎ በተዘጋጀ ባለ ብዙ-ተቋም አርክቴክቸር አማካኝነት ታካሚዎችን ከተፈቀደላቸው እንክብካቤ ጋር ያገናኛል።",
      fromFirstVisit: "ከመጀመሪያው ጉብኝት እስከ የተሳሰረ እንክብካቤ",
      howItWorks: "MyHealthID እንዴት እንደሚሰራ",
      identify: "1. ማንነት ማረጋገጥ",
      identifyDesc: "የታካሚውን MyHealthID መፍጠር ወይም ማረጋገጥ",
      triage: "2. ምርመራ (Triage)",
      triageDesc: "መሠረታዊ የጤና መረጃዎችን መመዝገብ እና ቅድሚያ መስጠት",
      care: "3. እንክብካቤ",
      careDesc: "የመቀበያ፣ ምርመራ፣ ሐኪም፣ ላብራቶሪ እና ፋርማሲን ማገናኘት",
      coordinate: "4. ማቀናጀት",
      coordinateDesc: "በተቋማት መካከል የተፈቀደ የመረጃ ልውውጥን መደገፍ"
    },
    registration: {
      title: "የዜጎች ምዝገባ",
      subtitle: "አዲስ ደህንነቱ የተጠበቀ የዜጎች የጤና መዝገብ ይክፈቱ — Hybrid Identity Bridge",
      identityVerification: "የማንነት ማረጋገጫ",
      identitySelectionDesc: "ይህን ዜጋ እንዴት መለየት ይፈልጋሉ?",
      faydaIdTitle: "ፋይዳ ብሔራዊ መታወቂያ",
      faydaIdDesc: "ዜጋው የ12-ዲጂት ፋይዳ መታወቂያ አለው",
      faydaPathTitle: "የፋይዳ ብሔራዊ መታወቂያ መንገድ",
      faydaPathDesc: "የዜጋውን የ12-ዲጂት ፋይዳ መታወቂያ ከታች ያስገቡና ያረጋግጡ",
      faydaVerificationRequired: "የፋይዳ ማረጋገጫ ያስፈልጋል",
      faydaUnlockText: "ሙሉ የምዝገባ ፎርሙን ለመክፈት እባክዎ ከላይ ያለውን የፋይዳ መታወቂያ ያረጋግጡ።",
      noIdTitle: "ብሔራዊ መታወቂያ የለኝም",
      noIdDesc: "ልዩ MyHealthID ይፍጠሩ — ማንም ዜጋ አይገለልም",
      noIdPathTitle: "በራስ-ሰር የሚፈጠር የMyHealthID መንገድ",
      noIdPathDesc: "ልዩ የውስጥ መለያ (UUID) በራስ-ሰር ይፈጠራል",
      noIdBadgeText: "በምዝገባ ወቅት ለዚህ ዜጋ ልዩ MyHealthID በራስ-ሰር ይፈጠራል። መታወቂያ አያስፈልግም።",
      change: "ቀይር",
      completeRegistration: "የዜጎች ምዝገባን ያጠናቅቁ",
      registering: "ዜጋውን በመመዝገብ ላይ...",
      demographicsTitle: "1. የዜጋው ግላዊ መረጃ",
      addressTitle: "2. አድራሻ እና የመገናኛ መረጃ",
      visitTitle: "3. የመጡበት ምክንያት",
      duplicateWarning: "ይፋዊ የጤና መገለጫ ከዚህ መረጃ ጋር ቀደም ሲል ተያይዟል። እባክዎ በኤስኤምኤስ ኦቲፒ (SMS OTP) በአስተማማኝ ሁኔታ ለማረጋገጥ ወደ መግቢያ / ፖርታል ፓነል ይሂዱ።",
      goToSignIn: "ወደ መግቢያ ይሂዱ",
      scheduleVisitTitle: "ክሊኒካዊ ቀጠሮ ይያዙ",
      scheduleVisitDesc: "የተመላላሽ ታካሚ ቀጠሮ ይያዙ ወይም ለምርመራ ወረፋ ይግቡ።",
      enterPortalTitle: "ወደ ዜጋው ፖርታል ይግቡ",
      enterPortalDesc: "ደህንነቱ የተጠበቀ የህክምና መዝገቦችን እና ታሪክን ይመልከቱ።"
    },
    login: {
      title: "የጤና ባለሙያዎች ፖርታል",
      subtitlePre: "ወደ MyHealth",
      subtitlePost: " ክሊኒክ ኔትወርክ ለመግባት ያረጋግጡ",
      emailLabel: "የሙያ ኢሜይል / የተጠቃሚ ስም",
      passwordLabel: "የይለፍ ቃል",
      roleLabel: "የመዳረሻ ሚና",
      secureLogin: "በአስተማማኝ ሁኔታ ይግቡ",
      selectCreds: "መረጃዎን ይምረጡ...",
      simNote: "ማሳሰቢያ፡ የማስመሰል ሁነታ ነቅቷል። ለማሳያ ማንኛውም መረጃ ተቀባይነት አለው።"
    },
    signin: {
      title: "የዜጎች መግቢያ ፖርታል",
      subtitle: "የእርስዎን MyHealthID ወይም ፋይዳ ብሔራዊ መታወቂያ በመጠቀም ወደ ጤና ዳሽቦርድዎ ይግቡ።",
      idLabel: "ፋይዳ መታወቂያ ወይም MyHealthID (MHI-)",
      idPlaceholder: "ምሳሌ: MHI-... ወይም የ12-ዲጂት ፋይዳ መታወቂያ",
      accessButton: "ወደ ጤና ዳሽቦርድ ይግቡ",
      notFoundTitle: "መዝገብ አልተገኘም",
      notFoundDesc: "በዚህ መታወቂያ የተመዘገበ ዜጋ አልተገኘም። እባክዎ መታወቂያውን ያረጋግጡ ወይም አዲስ መገለጫ ለመፍጠር ወደ የዜጎች ምዝገባ ገጽ ይሂዱ።",
      registerLink: "ወደ የዜጎች ምዝገባ ይሂዱ",
      otpTitle: "የማረጋገጫ ኮድ ያስገቡ",
      otpSubtitle: "ባለ 6-አሃዝ የማረጋገጫ ኮድ በስልክዎ ላይ ልከናል::",
      otpLabel: "ባለ 6-አሃዝ ኮድ",
      otpPlaceholder: "ምሳሌ: 123456",
      verifyButton: "አረጋግጥ እና ወደ ዳሽቦርድ ግባ",
      verifying: "ኮዱን በመፈተሽ ላይ...",
      resendButton: "ኮድ ድጋሚ ላክ",
      resendCountdown: "ኮድ ድጋሚ ላክ ({seconds} ሰ)",
      backButton: "ወደ መግቢያ ተመለስ",
      otpSentTo: "የማረጋገጫ ኮድ ወደ {phone} ተልኳል",
      invalidOtp: "የማረጋገጫ ኮዱ ትክክል አይደለም ወይም ጊዜው አልፏል።",
      tooManyAttempts: "ብዙ ሙከራዎች ተደርገዋል። መዳረሻው ታግዷል።"
    },
    profile: {
      title: "የዜጎች መገለጫ ራስ-አስተዳደር",
      subtitle: "የመገናኛ እና የማንነት ዝርዝሮችዎን በአስተማማኝ ሁኔታ ያዘምኑ።",
      editButton: "መገለጫ አርትዕ",
      saveButton: "ለውጦችን አስቀምጥ",
      cancelButton: "ሰርዝ",
      fullNameLabel: "ሙሉ ስም",
      phoneLabel: "ስልክ ቁጥር",
      dobLabel: "የትውልድ ቀን",
      successMessage: "መገለጫው በተሳካ ሁኔታ ተዘምኗል!",
      errorMessage: "መገለጫውን ማዘመን አልተሳካም። እባክዎ እንደገና ይሞክሩ።",
      backToRecords: "ወደ ክሊኒካዊ መዝገቦች ተመለስ"
    },
    privacy: {
      title: "ግላዊነት እና የዳታ ቁጥጥር",
      subtitle: "የጤና ዳታዎ የእርስዎ ነው። 누가 እንደሚያየው ይቆጣጠሩ።",
      restrictToggle: "Restrict Access",
      restrictToggleAm: "መረጃን መገደብ",
      unrestrictToggle: "Allow Access",
      unrestrictToggleAm: "መዳረሻ ፍቀድ",
      restrictedBadge: "የተገደበ",
      openBadge: "ክፍት",
      auditLogTitle: "የመዳረሻ ምርመራ መዝገብ",
      auditLogSubtitle: "የጤና ባለሙያ መዝገቦቹን ሲያይ፣ እዚህ ይመዘገባል።",
      colProfessional: "ባለሙያ",
      colFacility: "ተቋም",
      colRole: "ሚና",
      colAction: "ድርጊት",
      colTimestamp: "ጊዜ",
      noLogs: "እስካሁን ምንም የመዳረሻ ክስተቶች አልተመዘገቡም።",
      breakGlass: "በታካሚ የተገደበ መዳረሻ",
      breakGlassDesc: "ይህ ታካሚ ወደ ክሊኒካዊ መዝገቦቻቸው መዳረሻን ገድቧል።",
      breakGlassBtn: "አስቸኳይ ልዩ ፈቃድ ይጠይቁ",
      breakGlassConfirm: "አስቸኳይ ልዩ ፈቃድ ተሰጥቷል — መዳረሻ ተፈቅዷል እና ተመዝግቧል",
    },
    registrationV2: {
      pageTitle: "ታካሚ ይመዝገቡ",
      pageSubtitle: "አዲስ MyHealthID የታካሚ መዝገብ ይፍጠሩ።",
      // Mode Selector
      modeFayda: "ፋይዳ መታወቂያ",
      modeFaydaDesc: "ፋይዳ ብሔራዊ መታወቂያ ይጠቀሙ",
      modeNoId: "ብሔራዊ መታወቂያ የለም",
      modeNoIdDesc: "ደህንነቱ የተጠበቀ MyHealthID ይፍጠሩ",
      modeEmergency: "አስቸኳይ",
      modeEmergencyDesc: "ለድንገተኛ ሕክምና ፈጣን ምዝገባ",
      faydaUnavailable: "በዚህ አካባቢ ፋይዳ ማረጋጊያ አይገኝም።",
      faydaSandboxNote: "የሙከራ ሁነታ — ማረጋጊያ የምርት የመንግስት ዳታ አይደለም።",
      // Fayda flow
      faydaStepBack: "ደረጃ 1: የፋይዳ ካርዱ ጀርባ ላይ ያለውን QR ኮድ ይቃኙ",
      faydaStepFront: "ደረጃ 2: የካርዱን ፊት ይፎቷ",
      faydaStepConfirm: "ደረጃ 3: ማንነትን ያረጋግጡ",
      finLabel: "የፋይዳ መለያ ቁጥር (FIN)",
      finPlaceholder: "በካርዱ ጀርባ ላይ ያለው 12-አሃዝ ቁጥር",
      fcnLabel: "የፋይዳ ካርድ ቁጥር (FCN)",
      fcnPlaceholder: "ከፊት ባርኮድ ላይ ያለው 16-አሃዝ ቁጥር",
      verifyManual: "አረጋግጥ",
      manualBypass: "FIN / FCN ይተይቡ",
      scanBack: "ካርዱን ጀርባ ቃኝ",
      scanFront: "ካርዱን ፊት ፎቶ አንሳ",
      confirmIdentity: "ማንነትን አረጋግጥ",
      verificationSuccess: "ማንነት ተረጋግጧል",
      verifiedFrom: "ስም፣ የትውልድ ቀን እና ጾታ ከፋይዳ መዝገብ ተረጋግጠዋል።",
      // Basic info
      sectionBasicInfo: "የታካሚ መረጃ",
      fullNameLabel: "ሙሉ ስም",
      fullNamePlaceholder: "የታካሚው ሙሉ ስም",
      sexLabel: "ጾታ",
      sexMale: "ወንድ",
      sexFemale: "ሴት",
      dobLabel: "የትውልድ ቀን",
      ageLabel: "ዕድሜ",
      agePlaceholder: "ዕድሜ በዓመት",
      ageFromDob: "ዕድሜ (ከትውልድ ቀን የተሰላ)",
      phoneLabel: "ስልክ ቁጥር",
      phonePlaceholder: "09... (አማራጭ)",
      // Address
      sectionAddress: "አድራሻ",
      regionLabel: "ክልል",
      regionPlaceholder: "ለምሳሌ አዲስ አበባ፣ አማራ...",
      addressOptional: "ተጨማሪ የአድራሻ ዝርዝሮች (አማራጭ)",
      zoneLabel: "ዞን / ክፍለ ከተማ",
      woredaLabel: "ወረዳ",
      kebeleLabel: "ቀበሌ",
      // Portal access
      portalAccessTitle: "የኦንላይን መዳረሻ (አማራጭ)",
      portalAccessDesc: "ታካሚው የጤና መዝገቦቹን ኦንላይን እንዲያዩ የይለፍ ቃል ያዘጋጁ። ይህ በኋላ ሊደረግ ይችላል።",
      passwordLabel: "የይለፍ ቃል ይፍጠሩ",
      confirmPasswordLabel: "የይለፍ ቃል ያረጋግጡ",
      passwordPlaceholder: "ቢያንስ 6 ቁምፊዎች",
      confirmPasswordPlaceholder: "የይለፍ ቃሉን ደጋግሙ",
      skipPortal: "ዝለሉ — በኋላ ያዘጋጁ",
      setPassword: "የይለፍ ቃል አዘጋጅ",
      showPassword: "አሳይ",
      hidePassword: "ደብቅ",
      // Emergency
      emergencyTitle: "አስቸኳይ ፈጣን ምዝገባ",
      emergencyDesc: "ዝቅተኛ መረጃ — ታካሚው ወዲያውኑ ወደ አስቸኳይ ወረፋ ይገባሉ።",
      emergencyNameLabel: "የታካሚ ስም",
      emergencyNamePlaceholder: "ሙሉ ስም (ቢያንስ 2 ቁምፊዎች)",
      emergencyPhoneLabel: "ስልክ (አማራጭ)",
      emergencyPhonePlaceholder: "09...",
      emergencySubmit: "አስቸኳይ ታካሚ ይመዝገቡ",
      emergencyRegistering: "በምዝገባ ላይ...",
      // Submit / Review
      completeRegistration: "ምዝገባን ይጨርሱ",
      registering: "በምዝገባ ላይ...",
      // Duplicate warning
      duplicateWarning: "ከዚህ መረጃ ጋር ቀደም ሲል የታካሚ መዝገብ አለ።",
      duplicateGoSignIn: "ይግቡ →",
      // Success
      successTitle: "ታካሚው ተመዝግቧል",
      mhidLabel: "MyHealthID",
      mhidExplainer: "ይህ ቁጥር ታካሚውን በሁሉም MyHealthID አገልግሎቶች ይለያል። እባክዎ ያስቀምጡ ወይም QR ኮዱን ቃኙ።",
      copyId: "ቅዳ",
      copied: "ተቀድቷል!",
      queueLabel: "ወረፋ",
      queuePosition: "ቦታ",
      queueAdded: "ወደ ወረፋ ተጨምሯል",
      priorityLabel: "ቅድሚያ",
      priorityEmergency: "አስቸኳይ",
      priorityUrgent: "ፈጣን",
      priorityRoutine: "ተራ",
      wardLabel: "ክፍል",
      // Next actions
      actionTriage: "ወደ ምርመራ ቀጥሉ",
      actionBookAppointment: "ቀጠሮ ይያዙ",
      actionOpenPortal: "ፖርታል ይክፈቱ",
      actionRegisterAnother: "ሌላ ታካሚ ይመዝገቡ",
      actionSetupPortal: "የኦንላይን መዳረሻ ያዘጋጁ",
    },
  }
};
